#로봇 크기 
footprint: [[-0.15, -0.25], [-0.15, 0.25], [0.15, 0.25], [0.15, -0.25]] #가로 세로 각각 0.6m로 가정 


obstacle_layer: #장애물 레이어 
  enabled: true 
  obstacle_range: 2.0 #장애물 감지 최대 거리 (m)
  raytrace_range: 2.0 #장애물이 사라진 공간을 지우는 거리 (m)
  #inflation_radius: 0.2 #장애물 주변 생성 안전 버퍼크기 (m)
  track_unknown_space: false #true = unknown_space를 위험 구역으로 간주-> 피함 , false = 안전한 공간으로 간주 -> 진입 가능 

static_layer:
  enabled: true

inflation_layer: #장애물 주변 안전 버퍼 (m)
  enabled: true
  inflation_radius: 0.05

