global_costmap:
  global_frame: map #기준 프레임 
  robot_base_frame: base_link #로봇 기준 프레임
  update_frequency: 2.0 #비용맵 업데이트 주기 (Hz)
  publish_frequency: 2.0 #비용맵 발행 주기 (Hz)
  #width: 50.0  # 전역 비용맵의 가로 길이 (m)
  #height: 50.0  # 전역 비용맵의 세로 길이 (m)
  #resolution: 0.05  # 그리드 셀 크기 (m 단위)
  static_map: true  # 정적 맵 사용 여부 (SLAM아니면 true)
  track_unknown_space: false  #  미탐색 구역을 피하도록 설정

  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

#obstacle_layer:
#  enabled: true #장애물 레이어 활성화
#  obstacle_range: 2.0 #장애물 인식 최대 거리 (m)
#  raytrace_range: 6.0 #장애물 트레이싱 (자유 공간 탐지) 범위 (m)
#  #inflation_radius: 0.1  # 장애물 주변 안전 거리 (버퍼)

static_layer:
  enabled: true # 정적 맵 레이어 활성화

inflation_layer:
  enabled: false
  inflation_radius: 0.05 # 장애물 주변의 팽창 반경

