
local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 5.0
  #width: 5.0  # 로컬 비용맵 크기 (좁은 영역)
  #height: 5.0
  #resolution: 0.05
  static_map: false  # 로컬 맵은 정적이지 않음
  rolling_window: true  # 로컬 비용맵이 계속 움직이도록 설정
  track_unknown_space: false   # 미탐색 구역도 진입 가능하게 하여 더 유연한 경로 생성
  max_global_plan_lookahead_dist: 3.0
  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}



obstacle_layer:
  enabled: true 
  observation_sources: laser_scan_sensor depth_camera_sensor
  
  laser_scan_sensor: #LIDAR
    data_type: LaserScan
    topic: /scan
    sensor_frame: laser
    marking: true
    clearing: true
    obstacle_range: 2 #최대 감지거리 (m)
    raytrace_range: 2 #장애물 제거 범위 (라이다 레이저를 따라 장애물 지우는 범위)
    #max_obstacle_height: 2.0  # 최대 장애물 높이
    #min_obstacle_height: 0.1  # 최소 장애물 높이

  depth_camera_sensor:
    data_type: PointCloud2
    topic: /camera/depth/color/points  # 실제 토픽 이름 확인 필요
    sensor_frame: camera_link   # 실제 프레임 이름 확인 필요
    marking: true
    clearing: true
    obstacle_range: 2 #최대 감지거리 (m)
    raytrace_range: 2 #장애물 제거 범위 
    #max_obstacle_height: 2.0
    #min_obstacle_height: 0.1

inflation_layer: #안전 버퍼 
  enabled: true
  inflation_radius: 0.1

