local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  
  footprint: [[-0.23, -0.19], [-0.23, 0.19], [0.23, 0.19], [0.23, -0.19]]
  
  # 로컬 costmap 갱신 주기
  update_frequency: 15.0     # Hz
  publish_frequency: 15.0     # RViz 등으로 발행 주기 (약간 낮춰도 됨)
  
  # 실시간 장애물 반영 설정
  static_map: false
  rolling_window: true

  # 로컬 costmap의 크기 및 해상도
  width: 30.0       # 너무 크면 CPU 부담, 너무 작으면 시야 좁음
  height: 30.0
  resolution: 0.1 # 해상도가 너무 낮으면 부정확, 너무 높으면 계산량 많음
  
  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
    - {name: costmap_converter, type: "costmap_converter::CostmapToPolygonsDBSConcaveHull"}

  obstacle_layer:
    enabled: true
    track_unknown_space: false
    footprint_clearing_enabled: true
    max_obstacle_height: 2.0
    
  costmap_converter:
    enabled: true
