base_global_planner: "srl_dstar_lite/SrlDstarLite"
base_local_planner: "teb_local_planner/TebLocalPlannerROS"

# 🔹 실행 주기
planner_frequency: 5.0
controller_frequency: 10.0

# 🔹 시간 제한 (복구를 위한 설정)
planner_patience: 5.0
controller_patience: 3.0

# 🔹 진동 감지 및 방지
oscillation_timeout: 10.0
oscillation_distance: 0.2

# 🔹 장애물 회피 관련 설정
recovery_behavior_enabled: true
recovery_behaviors:
  - name: 'conservative_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'clearing_rotation'
    type: 'rotate_recovery/RotateRecovery'

# 🔹 Costmap 설정 (필수)
costmap_common:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  transform_tolerance: 0.5
  inflation_radius: 0.3
  footprint_padding: 0.02

