# use rolling window version of costmap, as local costmap is not static
rolling_window: false
# local map will be publish at modrate frequency of 10
publish_frequency: 5.0
# width of the map in meters
width: 5.0
# height of the map in meters
height: 5.0
# resolution of the map in meters/cell
resolution: 0.10
# local costmap will operate in the map frame, transform between this and robot-base frame must be available
global_frame: map

static_map: false

# name of the frame at base-link of the spencer robot
robot_base_frame: base_link
# specifications for the footprint of the robot as polygon (in meters)
# footprint: [ [0.756, 0.455], [0.756, -0.455], [-0.791, -0.455], [-0.791, 0.455] ] # real footprint
# footprint: [[0.796, 0.495], [0.796, -0.495], [-0.831, -0.495], [-0.831, 0.495] ] # larger footprint

# Footprint for Daryl
# footprint: [[0.39, 0.27], [0.39, -0.27], [0.24, -0.41], [-0.24, -0.41], [-0.39, -0.27], [-0.39, 0.27], [-0.24, 0.41], [0.24, 0.41]]
# Bigger footprint for Daryl
footprint: [[0.49, 0.37], [0.49, -0.37], [0.34, -0.51], [-0.34, -0.51], [-0.49, -0.37], [-0.49, 0.37], [-0.34, 0.51], [0.34, 0.51]]

# for local plannign we will use only obstacles, inflation layers
plugins:
 - {name: static_map, type: "costmap_2d::StaticLayer"}
 - {name: obstacles, type: "costmap_2d::ObstacleLayer"}
 - {name: inflater, type: "costmap_2d::InflationLayer"}
# sources for obstacle observation and their data types
obstacles:
    observation_sources: /spencer/sensors/laser_rear/echo0  /spencer/sensors/laser_front/echo0
    /spencer/sensors/laser_rear/echo0: {data_type: LaserScan, sensor_frame: /rear_laser, marking: true, clearing: true}
    /spencer/sensors/laser_front/echo0: {data_type: LaserScan, sensor_frame: /front_laser, marking: true, clearing: true}
# to better protect the robot in planning safe
inflater:
    observation_sources: /spencer/sensors/laser_rear/echo0 /spencer/sensors/laser_front/echo0
    /spencer/sensors/laser_rear/echo0: {data_type: LaserScan, sensor_frame: /front_laser, marking: true, clearing: true, map_type: costmap}
    /spencer/sensors/laser_front/echo0: {data_type: LaserScan, sensor_frame: /rear_laser, marking: true, clearing: true, map_type: costmap}
    inflation_radius: 0.05