obstacle_layer:
  enabled: true
  observation_sources: laser_scan_sensor depth_camera_sensor

  laser_scan_sensor:
    sensor_frame: laser
    data_type: LaserScan
    topic: /scan
    marking: true
    clearing: true
    obstacle_range: 2.0
    raytrace_range: 3.0

  depth_camera_sensor:
    sensor_frame: camera_link
    data_type: PointCloud2
    topic: /camera/depth/color/points
    marking: true
    clearing: true
    obstacle_range: 2.5
    raytrace_range: 3.0
