costmap:
  transform_tolerance: 2.0
  observation_sources: laser_scan_sensor depth_camera_sensor

  laser_scan_sensor:
    sensor_frame: laser
    data_type: LaserScan
    topic: /scan
    marking: true
    clearing: true
    obstacle_range: 2.0
    raytrace_range: 3.0
    expected_update_rate: 10.0

  depth_camera_sensor:
    sensor_frame: camera_depth_optical_frame
    data_type: PointCloud2
    topic: /camera/depth/color/points
    marking: true
    clearing: true
    obstacle_range: 2.0
    raytrace_range: 3.0
    expected_update_rate: 15.0

