footprint: [[-0.3, -0.3], [-0.3, 0.3], [0.3, 0.3], [0.3, -0.3]]
robot_radius: 0.2

obstacle_layer:
  enabled: true
  obstacle_range: 2.5
  raytrace_range: 3.0
  inflation_radius: 0.55
  track_unknown_space: true

static_layer:
  enabled: true

inflation_layer:
  enabled: true
  inflation_radius: 0.55

