local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 5.0
  width: 5.0  # 로컬 비용맵 크기 (좁은 영역)
  height: 5.0
  resolution: 0.05
  static_map: false  # 로컬 맵은 정적이지 않음
  rolling_window: true  # 로컬 비용맵이 계속 움직이도록 설정
  track_unknown_space: false  # 로컬에서는 장애물만 탐색

  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

obstacle_layer:
  enabled: true
  obstacle_range: 3.0
  raytrace_range: 3.5
  inflation_radius: 0.5

inflation_layer:
  enabled: true
  inflation_radius: 0.5

