local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 5.0
  rolling_window: true
  track_unknown_space: false
  max_global_plan_lookahead_dist: 3.0
  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  observation_sources: laser_scan_sensor depth_camera_sensor

obstacle_layer:
  enabled: true
  track_unknown_space: false
  footprint_clearing_enabled: true
  max_obstacle_height: 2.0

  laser_scan_sensor:  # LiDAR
    sensor_frame: laser
    data_type: LaserScan
    topic: /scan
    marking: true
    clearing: true
    obstacle_range: 2.0
    raytrace_range: 3.0

  depth_camera_sensor:  # Realsense Depth Camera
    sensor_frame: camera_link
    data_type: PointCloud2
    topic: /camera/depth/color/points
    marking: true
    clearing: true
    obstacle_range: 2.5
    raytrace_range: 3.5

