TebLocalPlannerROS:
  include_costmap_obstacles: True
  costmap_obstacles_behind_robot_dist: 1.5
  obstacle_poses_affected: 15
  dynamic_obstacle_inflation_dist: 0.6
  include_dynamic_obstacles: True
  costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSMCCH" 
  costmap_converter_spin_thread: True
  costmap_converter_rate: 5
  
  #costmap_obstacles_topic: /move_base/local_costmap/obstacles
